### ISSUE TITLE
"readonlyREST" mode in "authentication preferences" for reports

### ISSUE THREAD

**Issue by lbesuchet** [lmangani/sentinl#571]
**Kibana version:**
6.2.4

**Elasticsearch version:**
6.2.4

Do you have any plan to provide a "readonlyREST" mode in "authentication preferences" for reports ?
Would be great ;-)

**Comment by sergibondarenko** [comment]
@lbesuchet did you try Sentinl report `customselector` authentication mode to pass readonlyREST login form?

```
{
  "actions": {
    "report_admin": {
      "throttle_period": "0h0m1s",
      "report": {
        ...
        "auth": {
          "active": true,
          "mode": "customselector",
          "username": "admin",
          "password": "12345",
          "selector_username": "form input[id='usr']",
          "selector_password": "form input[id='pwd']",
          "selector_login_btn": "form input[type='submit']"
        }
...
``` 
Here is the doc https://github.com/sirensolutions/sentinl/blob/master/docs/Authentication.md#custom-login-page-authentication

Make sure you put valid CSS selectors. See [this tutorial](https://developers.google.com/web/updates/2015/05/search-dom-tree-by-css-selector) to find out how to find a selector using Chrome.
Please let me know the result.

**Comment by lbesuchet** [comment]
@sergibondarenko 
Hi,
Thanks for your quick reply. Yes, the custom selector works, but:
- it would be nice to have this pre-configured in the dropdown
- I could not succeed making the report work with horseman. Hopefully puppeteer works fine, but tough to install the missing libs on my kibana docker image.

**Comment by sergibondarenko** [comment]
> Yes, the custom selector works ...
> I could not succeed making the report work with horseman

Does it work or not? Do you see any related error in the Kibana log? Paste the full error text here.

**Comment by sergibondarenko** [comment]
> ...tough to install the missing libs on my kibana docker image.

Mybe this helps you to install puppeteer in the docker image https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-in-docker

**Comment by sergibondarenko** [comment]
Do you use some Kibana security solution, X-Pack? 

Horseman and PhantomJS are already bundled in Sentinl pkg. In order to use them you should have only theses things in the Dockerfile
```
USER root
RUN yum update -y && yum install -y fontconfig freetype net-tools && yum clean all
# or whatever user you use to run the Kibana docker image
USER kibana
```

Btw, **there is a bug in the pkg you use**, report screenshot can't be saved due to an error in the Elasticsearch mappings. It was fixed some time ago but not synchronized to master. I have synched the fix and build a new pkg for you, **use the new pkg please**  https://github.com/sirensolutions/sentinl/releases/download/tag-6.2.4/sentinl-v6.2.4.zip

**Comment by lbesuchet** [comment]
Only X-Pack reporting is enabled.
I tried your dockerfile along with your new pkg, but still have issues with both horseman:
`{"type":"log","@timestamp":"2018-10-10T11:38:15Z","tags":["error","Sentinl","5d02bbe0-cbcb-11e8-8575-df3ce6c3f1eb"],"pid":1,"message":"watcher_filereader, report action: Error: exec: Error: exec \"horseman\" report: Error: spawn EACCES"}`
and puppeteer:
`{"type":"log","@timestamp":"2018-10-10T11:43:57Z","tags":["error","Sentinl","5d02bbe0-cbcb-11e8-8575-df3ce6c3f1eb"],"pid":1,"message":"watcher_filereader, report action: Error: exec: Error: exec \"puppeteer\" report: Error: Error: Failed to launch chrome!\n/usr/share/kibana/plugins/sentinl/node_modules/puppeteer/.local-chromium/linux-564778/chrome-linux/chrome: error while loading shared libraries: libX11.so.6: cannot open shared object file: No such file or directory\n\n\nTROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md\n"}`

Anyway, with my dockerfile & puppeteer, it's working fine.

**Comment by sergibondarenko** [comment]
> Anyway, with my dockerfile & puppeteer, it's working fine.

I'm glad to here that it works for you! Could you please paste here your Dockerfile? It would be wonderful to have it in the issues history.

> `...exec \"horseman\" report: Error: spawn EACCES`...

It means there is no access to the phantomjs or the access is prohibited. I would like to try your Dockerfile.

**Comment by lbesuchet** [comment]
Here is the Dockerfile (with readonlyREST):

```
USER root
#requested by sentinl report (netstat) + sentinl puppeteer
RUN yum update -y && yum install -y net-tools && \
    yum install -y cups-libs dbus-glib libXrandr libXcursor libXinerama cairo cairo-gobject pango gtk3 libXScrnSaver alsa-lib && yum clean all

USER kibana
COPY readonlyrest_kbn_enterprise-1.16.26_es6.2.4.zip /var/tmp/
COPY sentinl-v6.2.4.zip /var/tmp/
RUN /usr/share/kibana/bin/kibana-plugin install file:///var/tmp/readonlyrest_kbn_enterprise-1.16.26_es6.2.4.zip && \
    /usr/share/kibana/bin/kibana-plugin install file:///var/tmp/sentinl-v6.2.4.zip
```
